/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apical_dvr_ffRecorder */

#ifndef _Included_com_apical_dvr_ffRecorder
#define _Included_com_apical_dvr_ffRecorder

extern JavaVM* g_jvm;
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM*, void*);
JNIEXPORT JNIEnv* get_jni_env(void);

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeInitCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeInitCallback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeInit
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_apical_dvr_ffRecorder_nativeInit
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeGetMicMute
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_apical_dvr_ffRecorder_nativeGetMicMute
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeSetMicMute
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeSetMicMute
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeResetCamera
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeResetCamera
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeSetWatermark
 * Signature: (JIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeSetWatermark
  (JNIEnv *, jclass, jlong, jint, jint, jint, jstring);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeSetPreviewWindow
 * Signature: (JILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeSetPreviewWindow
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeSetPreviewTarget
 * Signature: (JILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeSetPreviewTarget
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeStartPreview
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeStartPreview
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeStopPreview
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeStopPreview
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeStartRecording
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeStartRecording
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeStopRecording
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeStopRecording
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeSetAudioSource
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeSetAudioSource
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeSetVideoSource
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeSetVideoSource
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_apical_dvr_ffRecorder
 * Method:    nativeTakePhoto
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_ffRecorder_nativeTakePhoto
  (JNIEnv *, jclass, jlong, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
