/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apical_dvr_MediaRecorder */

#ifndef _Included_com_apical_dvr_MediaRecorder
#define _Included_com_apical_dvr_MediaRecorder
#ifdef __cplusplus
extern "C" {
#endif

extern JavaVM* g_jvm;
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM*, void*);
JNIEXPORT JNIEnv* get_jni_env(void);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_apical_dvr_MediaRecorder_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeGetMicMute
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_apical_dvr_MediaRecorder_nativeGetMicMute
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeSetMicMute
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeSetMicMute
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeResetCamera
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeResetCamera
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeSetPreviewWindow
 * Signature: (JILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeSetPreviewWindow
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeSetPreviewTarget
 * Signature: (JILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeSetPreviewTarget
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeStartPreview
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeStartPreview
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeStopPreview
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeStopPreview
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeStartRecording
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeStartRecording
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeStopRecording
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeStopRecording
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeSetAudioSource
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeSetAudioSource
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeSetVideoSource
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeSetVideoSource
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeTakePhoto
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeTakePhoto
  (JNIEnv *, jclass, jlong, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
