/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_apical_dvr_MediaRecorder.h"
/* Header for class com_apical_dvr_MediaRecorder */

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_apical_dvr_MediaRecorder_nativeInit
  (JNIEnv *env, jclass clazz)
{
    return 0;
}

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeFree
  (JNIEnv *env, jclass, jlong ctxt)
{
}

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeResetCamera
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeResetCamera
  (JNIEnv *env, jclass, jlong ctxt, jint w, jint h, jint, jint frate)
{
}

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeSetPreviewWindow
 * Signature: (JILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeSetPreviewWindow
  (JNIEnv *env, jclass, jlong ctxt, jint camidx, jobject win)
{
}

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeSetPreviewTarget
 * Signature: (JILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeSetPreviewTarget
  (JNIEnv *env, jclass, jlong ctxt, jint camidx, jobject win)
{
}

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeStartPreview
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeStartPreview
  (JNIEnv *env, jclass, jlong ctxt, jint camidx)
{
}

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeStopPreview
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeStopPreview
  (JNIEnv *env, jclass, jlong ctxt, jint camidx)
{
}

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeStartRecording
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeStartRecording
  (JNIEnv *env, jclass, jlong ctxt, jint encidx, jstring filename)
{
}

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeStopRecording
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeStopRecording
  (JNIEnv *env, jclass, jlong ctxt, jint encidx)
{
}

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeSetAudioSource
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeSetAudioSource
  (JNIEnv *env, jclass, jlong ctxt, jint encidx, jint source)
{
}

/*
 * Class:     com_apical_dvr_MediaRecorder
 * Method:    nativeSetVideoSource
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_apical_dvr_MediaRecorder_nativeSetVideoSource
  (JNIEnv *env, jclass, jlong ctxt, jint encidx, jint source)
{
}
