CONFIG_FFJPEGDEC_TYPE := ljp

ifeq ($(CONFIG_FFJPEGDEC_TYPE), ljp)
    LOCAL_CFLAGS += -DCONFIG_FFJPEGDEC_LJP
endif

ifeq ($(CONFIG_FFJPEGDEC_TYPE), a31)
    LOCAL_CFLAGS += -DCONFIG_FFJPEGDEC_A31
endif
